apiVersion: v2
description: Helm chart for deploying the Azimuth Portal.
name: azimuth
type: application
# The version and appVersion are updated by the chart build script
version: 0.1.0
appVersion: master
