[tox]
minversion = 4.0.0
# We run autofix last, to ensure CI fails,
# even though we do our best to autofix locally
envlist = py3,ruff,codespell,autofix
# TODO: fix mypy and add to envlist
skipsdist = True

[testenv]
runner = uv-venv-lock-runner
setenv =
   PYTHONWARNINGS=default::DeprecationWarning
   DJANGO_SETTINGS_MODULE=tests.settings
changedir = {toxinidir}/api
commands = python manage.py test tests {posargs}

[testenv:autofix]
commands =
    ruff format {tox_root}/api
    codespell {tox_root}/api -w --ignore-words={tox_root}/.codespellignore
    ruff check {tox_root}/api --fix
[testenv:black]
# TODO: understand why ruff doesn't fix
# line lengths as well as black does
commands = black {tox_root}/api {posargs}

[testenv:codespell]
commands = codespell {tox_root}/api --ignore-words={tox_root}/.codespellignore {posargs}

[testenv:ruff]
description = Run Ruff checks
commands =
    ruff check {tox_root}/api
    ruff format {tox_root}/api --check

[testenv:venv]
commands = {posargs}

[testenv:cover]
setenv =
    {[testenv]setenv}
    VIRTUAL_ENV={envdir}
changedir = {toxinidir}/api
commands =
    coverage run --source azimuth,azimuth_auth,azimuth_site manage.py test tests {posargs}
    coverage html -d {toxinidir}/cover
    coverage xml -o {toxinidir}/cover/coverage.xml
    coverage report

[testenv:mypy]
commands = mypy {tox_root}/api {posargs}
