{{/*
This configmap must always exist, even if apps are not enabled, as it is used to populate
environment variables in subcharts.

If apps are not enabled, those environment variables will be empty and so will be ignored
by configomatic.
*/}}
{{- if and .Values.tags.kubernetes (index .Values "capi-operator" | dig "enabled" true) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azimuth.componentname" (list . "apps-conf") }}
  labels: {{ include "azimuth.componentLabels" (list . "apps-conf") | nindent 4 }}
data:
  {{- if .Values.tags.apps }}
  baseDomain: {{ tpl .Values.apps.baseDomain . | quote }}
  sshdHost: {{ tpl .Values.apps.sshdHost . | quote }}
  sshdPort: {{ tpl (toString .Values.apps.sshdPort) . | quote }}
  registrarExternalUrl: {{ tpl .Values.apps.registrarExternalUrl . | quote }}
  registrarAdminUrl: {{ tpl .Values.apps.registrarAdminUrl . | quote }}
  {{- else }}
  baseDomain: ""
  sshdHost: ""
  sshdPort: ""
  registrarExternalUrl: ""
  registrarAdminUrl: ""
  {{- end }}
{{- end }}
