apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azimuth.componentname" (list . "theme") }}
  labels: {{ include "azimuth.componentLabels" (list . "theme") | nindent 4 }}
data:
  bootstrap.css: |
    @import url({{ .Values.theme.bootstrapCssUrl }});
    {{- with .Values.theme.customCss }}
    {{- . | nindent 4 }}
    {{- end }}
