{{- $global := deepCopy .Values.global.ingress }}
{{- $portal := deepCopy .Values.ingress }}
{{- $ingress := mergeOverwrite $global $portal }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "azimuth.fullname" . }}
  labels: {{ include "azimuth.labels" . | nindent 4 }}
  {{- $tlsAnnotations := $ingress.tls.enabled | ternary $ingress.tls.annotations dict }}
  {{- $annotations := mergeOverwrite $ingress.annotations $tlsAnnotations }}
  {{- with $annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if $ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ tpl $ingress.host . | quote }}
      secretName: {{ $ingress.tls.secretName | default (printf "%s-tls" (include "azimuth.fullname" .)) }}
  {{- end }}
  rules:
    - host: {{ tpl $ingress.host . | quote }}
      http:
        paths:
          # Send the /api, /auth and /static paths to the api
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "azimuth.componentname" (list . "api") }}
                port:
                  name: http
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "azimuth.componentname" (list . "api") }}
                port:
                  name: http
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: {{ include "azimuth.componentname" (list . "api") }}
                port:
                  name: http
          # Send everything else to the ui
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "azimuth.componentname" (list . "ui") }}
                port:
                  name: http
