SECRET_KEY: {{ .Values.settings.secretKey | required "No Django secret key specified"  }}
DEBUG: {{ .Values.settings.debug }}
CSRF_COOKIE_SECURE: {{ .Values.ingress.tls.enabled }}
{{- with .Values.settings.csrfCookieName }}
CSRF_COOKIE_NAME: {{ . }}
{{- end }}
SESSION_COOKIE_SECURE: {{ .Values.ingress.tls.enabled }}
{{- with .Values.settings.sessionCookieName }}
SESSION_COOKIE_NAME: {{ . }}
{{- end }}
{{- with .Values.settings.nextUrlCookieName }}
AZIMUTH_AUTH:
  NEXT_URL_COOKIE_NAME: {{ . }}
{{- end }}
