{{- $ingress := mergeOverwrite .Values.global.ingress .Values.ingress }}
SECRET_KEY: {{
  .Values.global.secretKey |
    default .Values.settings.secretKey |
    required "global.secretKey is required"
}}
DEBUG: {{ .Values.settings.debug }}
CSRF_COOKIE_SECURE: {{ $ingress.tls.enabled }}
{{- with .Values.settings.csrfCookieName }}
CSRF_COOKIE_NAME: {{ . }}
{{- end }}
SESSION_COOKIE_SECURE: {{ $ingress.tls.enabled }}
{{- with .Values.settings.sessionCookieName }}
SESSION_COOKIE_NAME: {{ . }}
{{- end }}
{{- with .Values.settings.nextUrlCookieName }}
AZIMUTH_AUTH:
  NEXT_URL_COOKIE_NAME: {{ . }}
{{- end }}
