{{-
  if (
    or
      (ne .Values.authentication.type "openstack")
      .Values.authentication.openstack.authUrl
  )
}}
{{- with .Values.authentication -}}
# New-style authentication configuration
# Authentication is defined by cloud type and reused by components as needed
AZIMUTH_AUTH:
  AUTH_TYPE: {{ .type }}
  {{- if eq .type "oidc" }}
  {{- with .oidc }}
  OIDC:
    ISSUER_URL: {{ required "OIDC issuer URL is required" .issuerUrl | quote }}
    USERID_CLAIM: {{ quote .claims.userid }}
    USERNAME_CLAIM: {{ quote .claims.username }}
    EMAIL_CLAIM: {{ quote .claims.email }}
    GROUPS_CLAIM: {{ quote .claims.groups }}
    CLIENT_ID: {{ required "OIDC client ID is required" .clientID | quote }}
    CLIENT_SECRET: {{ required "OIDC client secret is required" .clientSecret | quote }}
    {{- with .scope }}
    SCOPE: {{ quote . }}
    {{- end }}
    VERIFY_SSL: {{ ternary "true" "false" .verifySsl }}
  {{- end }}
  {{- else if eq .type "openstack" }}
  {{- with .openstack }}
  OPENSTACK:
    AUTH_URL: {{ required "OpenStack auth URL is required" .authUrl | quote }}
    {{- with .region }}
    REGION: {{ quote . }}
    {{- end }}
    INTERFACE: {{ quote .interface }}
    VERIFY_SSL: {{ ternary "true" "false" .verifySsl }}
    APPCRED_HIDDEN: {{ ternary "true" "false" .appcred.hidden }}
    {{- if .password.enabled }}
    PASSWORD_ENABLED: true
    {{- if empty .password.domains }}
    {{- fail "At least one OpenStack authentication domain must be specified" }}
    {{- else }}
    PASSWORD_DOMAINS:
      {{- range .password.domains }}
      - name: {{ required "domain name is required" .name | quote }}
        {{- with .label }}
        label: {{ quote . }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- if .federated.enabled }}
    FEDERATED_ENABLED: true
    {{- if empty .federated.identityProviders }}
    {{- fail "At least one OpenStack federated IDP must be specified" }}
    {{- else }}
    FEDERATED_IDENTITY_PROVIDERS:
      {{- range .federated.identityProviders }}
      - protocol: {{ required "IDP protocol is required" .protocol | quote }}
        {{- with .provider }}
        provider: {{ quote . }}
        {{- end }}
        {{- with .label }}
        label: {{ quote . }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- else }}
  {{- printf "Unrecognised authentication type - %s" .type | fail }}
  {{- end }}
{{- end }}
{{- else if .Values.authenticators }}
# Legacy authentication configuration
# Authenticators and session provider are specified separately
AZIMUTH_AUTH:
  AUTHENTICATORS:
    {{- range .Values.authenticators }}
    - NAME: {{ quote .name }}
      {{- with .label }}
      LABEL: {{ quote . }}
      {{- end }}
      {{- with .hidden }}
      HIDDEN: true
      {{- end }}
      AUTHENTICATOR:
        {{- if (eq .type "openstack-password") }}
        FACTORY: azimuth_auth.authenticator.openstack.PasswordAuthenticator
        PARAMS:
          AUTH_URL: {{ default $.Values.provider.openstack.authUrl .openstackPassword.authUrl }}
          DOMAINS:
            - name: {{ default $.Values.provider.openstack.domain .openstackPassword.domain }}
          VERIFY_SSL: {{ default $.Values.provider.openstack.verifySsl .openstackPassword.verifySsl }}
        {{- else if (eq .type "openstack-application-credential") }}
        FACTORY: azimuth_auth.authenticator.openstack.ApplicationCredentialAuthenticator
        PARAMS:
          AUTH_URL: {{ default $.Values.provider.openstack.authUrl .openstackApplicationCredential.authUrl }}
          VERIFY_SSL: {{ default $.Values.provider.openstack.verifySsl .openstackApplicationCredential.verifySsl }}
        {{- else if (eq .type "openstack-federation") }}
        FACTORY: azimuth_auth.authenticator.openstack.FederatedAuthenticator
        PARAMS:
          AUTH_URL: {{ default $.Values.provider.openstack.authUrl .openstackFederation.authUrl }}
          {{- if empty .openstackFederation.identityProviders }}
          {{- fail "No IDPs are defined" }}
          {{- end }}
          IDENTITY_PROVIDERS:
            {{- range .openstackFederation.identityProviders }}
            - name: {{ required "name is required for federated IDPs" .name | quote }}
              {{- with .label }}
              label: {{ quote . }}
              {{- end }}
              {{- with .provider }}
              provider: {{ quote . }}
              {{- end }}
              protocol: {{ required "protocol is required for federated IDPs" .protocol | quote }}
            {{- end }}
        {{- else }}
        {{- fail (printf "Unrecognised authenticator '%s'" .type) }}
        {{- end }}
    {{- end }}
  {{- if (eq .Values.provider.type "openstack") }}
  SESSION_PROVIDER:
    FACTORY: azimuth_auth.session.openstack.Provider
    PARAMS:
      AUTH_URL: {{ required "provider.openstack.authUrl is required" .Values.provider.openstack.authUrl }}
      {{- with .Values.provider.openstack.interface }}
      INTERFACE: {{ . }}
      {{- end }}
      VERIFY_SSL: {{ .Values.provider.openstack.verifySsl }}
  {{- else }}
  {{- fail (printf "Unrecognised cloud provider '%s'" .Values.provider.type) }}
  {{- end }}
{{- else }}
{{- fail "No authentication is defined" }}
{{- end }}
