{{- if empty .Values.authenticators }}
{{- fail "No authenticators are defined" }}
{{- end }}
AZIMUTH_AUTH:
  AUTHENTICATORS:
    {{- range .Values.authenticators }}
    - NAME: {{ quote .name }}
      {{- with .label }}
      LABEL: {{ quote . }}
      {{- end }}
      {{- with .hidden }}
      HIDDEN: true
      {{- end }}
      AUTHENTICATOR:
        {{- if (eq .type "openstack-password") }}
        FACTORY: azimuth_auth.authenticator.openstack.PasswordAuthenticator
        PARAMS:
          AUTH_URL: {{ default $.Values.provider.openstack.authUrl .openstackPassword.authUrl }}
          DOMAIN: {{ default $.Values.provider.openstack.domain .openstackPassword.domain }}
          VERIFY_SSL: {{ default $.Values.provider.openstack.verifySsl .openstackPassword.verifySsl }}
        {{- else if (eq .type "openstack-application-credential") }}
        FACTORY: azimuth_auth.authenticator.openstack.ApplicationCredentialAuthenticator
        PARAMS:
          AUTH_URL: {{ default $.Values.provider.openstack.authUrl .openstackApplicationCredential.authUrl }}
          VERIFY_SSL: {{ default $.Values.provider.openstack.verifySsl .openstackApplicationCredential.verifySsl }}
        {{- else if (eq .type "openstack-federation") }}
        FACTORY: azimuth_auth.authenticator.openstack.FederatedAuthenticator
        PARAMS:
          AUTH_URL: {{ default $.Values.provider.openstack.authUrl .openstackFederation.authUrl }}
          {{- if empty .openstackFederation.identityProviders }}
          {{- fail "No IDPs are defined" }}
          {{- end }}
          IDENTITY_PROVIDERS:
            {{- range .openstackFederation.identityProviders }}
            - name: {{ required "name is required for federated IDPs" .name | quote }}
              {{- with .label }}
              label: {{ quote . }}
              {{- end }}
              {{- with .provider }}
              provider: {{ quote . }}
              {{- end }}
              protocol: {{ required "protocol is required for federated IDPs" .protocol | quote }}
            {{- end }}
        {{- else }}
        {{- fail (printf "Unrecognised authenticator '%s'" .type) }}
        {{- end }}
    {{- end }}
