AZIMUTH:
  PROVIDER:
    {{- if (eq .Values.provider.type "openstack") }}
    FACTORY: azimuth.provider.openstack.Provider
    PARAMS:
      {{- with .Values.provider.openstack.internalNetTemplate }}
      INTERNAL_NET_TEMPLATE: {{ . | quote }}
      {{- end }}
      {{- with .Values.provider.openstack.externalNetTemplate }}
      EXTERNAL_NET_TEMPLATE: {{ . | quote }}
      {{- end }}
      CREATE_INTERNAL_NET: {{ .Values.provider.openstack.createInternalNet }}
      MANILA_PROJECT_SHARE_GB: {{ .Values.provider.openstack.manilaProjectShareGB }}
      {{- with .Values.provider.openstack.internalNetCidr }}
      INTERNAL_NET_CIDR: {{ . | quote }}
      {{- end }}
      {{- with .Values.provider.openstack.internalNetDNSNameservers }}
      INTERNAL_NET_DNS_NAMESERVERS: {{ toYaml . | nindent 8 }}
      {{- end }}
    {{- else }}
    {{- fail (printf "Unrecognised cloud provider '%s'" .Values.provider.type) }}
    {{- end }}
