{{- $component := "api" -}}
{{- $values := get .Values $component -}}
{{- $clusterEngine := .Values.clusterEngine -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azimuth.componentname" (list . $component) }}
  labels: {{ include "azimuth.componentLabels" (list . $component) | nindent 4 }}
spec:
  replicas: {{ $values.replicaCount }}
  selector:
    matchLabels: {{ include "azimuth.componentSelectorLabels" (list . $component) | nindent 6 }}
  template:
    metadata:
      labels: {{ include "azimuth.componentSelectorLabels" (list . $component) | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: {{ $component }}
        azimuth.stackhpc.com/settings-hash: {{ include (print $.Template.BasePath "/api/settings.yaml") . | sha256sum }}
        azimuth.stackhpc.com/theme-hash: {{ include (print $.Template.BasePath "/configmap-theme.yaml") . | sha256sum }}
        {{- with $values.podAnnotations }}
        {{ toYaml . | indent 8 | trim }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "azimuth.componentname" (list . $component) }}
      {{- with $values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{ toYaml $values.podSecurityContext | nindent 8 }}
      containers:
        {{- if $values.monitoring.enabled }}
        - name: statsd-exporter
          # image: {{ printf "%s:%s" $values.monitoring.statsd.image.repository $values.monitoring.statsd.image.tag }}
          image: prom/statsd-exporter:v0.23.0
          ports:
            - name: metrics
              containerPort: 9102
              protocol: TCP
          args:
            - "--statsd.mapping-config=/statsd/statsd.conf"
          volumeMounts:
            - name: statsd-config
              mountPath: /statsd/
        {{ end }}
        - name: {{ $component }}
          securityContext: {{ toYaml $values.securityContext | nindent 12 }}
          image: {{ printf "%s:%s" $values.image.repository (default .Chart.AppVersion $values.image.tag) }}
          imagePullPolicy: {{ $values.image.pullPolicy }}
          {{- if (and .Values.tags.clusters (eq $clusterEngine.type "awx")) }}
          env:
            - name: AWX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ required "clusterEngine.awx.passwordSecretName is required" $clusterEngine.awx.passwordSecretName | quote }}
                  key: password
            {{- with $clusterEngine.awx.adminPasswordSecretName }}
            - name: AWX_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ quote . }}
                  key: password
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_status/
              port: http
          readinessProbe:
            httpGet:
              path: /_status/
              port: http
          resources: {{ toYaml $values.resources | nindent 12 }}
          volumeMounts:
            - name: runtime-settings
              mountPath: /etc/azimuth/settings.d
              readOnly: true
            - name: theme-css
              mountPath: /var/azimuth/staticfiles/bootstrap.css
              subPath: bootstrap.css
              readOnly: true
            {{- if .Values.trustBundleConfigMapName }}
            - name: trust-bundle
              mountPath: /etc/azimuth/trust
              readOnly: true
            {{- end }}
            - name: tmp
              mountPath: /tmp
      {{- with $values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: runtime-settings
          secret:
            secretName: {{ include "azimuth.componentname" (list . $component) }}
        - name: theme-css
          configMap:
            name: {{ include "azimuth.componentname" (list . "theme") }}
        {{- if .Values.trustBundleConfigMapName }}
        - name: trust-bundle
          configMap:
            name: {{ .Values.trustBundleConfigMapName }}
        {{- end }}
        - name: tmp
          emptyDir: {}
        {{- if $values.monitoring.enabled }}
        - name: statsd-config
          configMap:
            name: statsd-metric-mapping
        {{ end }}
