{{- $component := "api" -}}
{{- $values := get .Values $component -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "azimuth.componentname" (list . $component) }}
  labels: {{ include "azimuth.componentLabels" (list . $component) | nindent 4 }}
spec:
  type: {{ $values.service.type }}
  ports:
    - name: http
      port: {{ $values.service.port }}
      targetPort: http
      protocol: TCP
    {{- if $values.monitoring.enabled }}
    - name: metrics
      port: {{ $values.monitoring.service.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector: {{ include "azimuth.componentSelectorLabels" (list . $component) | nindent 4 }}
