{{- $component := "api" -}}
{{- $values := get .Values $component -}}
{{- if $values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "azimuth.componentname" (list . $component) }}-statsd-exporter
  labels:
    {{- include "azimuth.componentLabels" (list . $component) | nindent 4 }}
    api.kubernetes.io/sub-component: {{ include "azimuth.componentname" (list . $component) }}-statsd-exporter
spec:
  type: ClusterIP
  ports:
    - port: {{ $values.monitoring.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector: {{ include "azimuth.componentSelectorLabels" (list . $component) | nindent 4 }}
{{ end }}