apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azimuth.componentname" (list . "api") }}
  labels: {{ include "azimuth.componentLabels" (list . "api") | nindent 4 }}
type: Opaque
# Use data because of https://github.com/helm/helm/issues/10010
# Not doing so means that AWX-related keys are not removed on transition to the CRD
data:
  01-django.yaml: |
    {{- tpl (.Files.Get "files/api/settings/01-django.yaml") . | b64enc | nindent 4 }}
  02-cloud-common.yaml: |
    {{- tpl (.Files.Get "files/api/settings/02-cloud-common.yaml") . | b64enc | nindent 4 }}
  03-cloud-authenticators.yaml: |
    {{- tpl (.Files.Get "files/api/settings/03-cloud-authenticators.yaml") . | b64enc | nindent 4 }}
  04-cloud-provider.yaml: |
    {{- tpl (.Files.Get "files/api/settings/04-cloud-provider.yaml") . | b64enc | nindent 4 }}
{{- if .Values.tags.apps }}
  05-apps.yaml: |
    {{- tpl (.Files.Get "files/api/settings/05-apps.yaml") . | b64enc | nindent 4 }}
{{- end }}
  06-ssh-key-store.yaml: |
    {{- tpl (.Files.Get "files/api/settings/06-ssh-key-store.yaml") . | b64enc | nindent 4 }}
{{- if not .Values.tags.kubernetes }}
  07-disable-kubernetes.yaml: |
    {{- tpl (.Files.Get "files/api/settings/07-disable-kubernetes.yaml") . | b64enc | nindent 4 }}
{{- end }}
{{- if .Values.tags.clusters }}
{{- if list "crd" "awx" | has .Values.clusterEngine.type }}
{{- if eq .Values.clusterEngine.type "awx" }}
  08-awx.yaml: |
    {{- tpl (.Files.Get "files/api/settings/08-awx.yaml") . | b64enc | nindent 4 }}
  09-awx-passwords.py: |
    {{- tpl (.Files.Get "files/api/settings/09-awx-passwords.py") . | b64enc | nindent 4 }}
{{- end }}
{{- else }}
{{- fail (printf "Unsupported cluster engine '%s'" .Values.clusterEngine.type) }}
{{- end }}
{{- else }}
  10-disable-caas.yaml: |
    {{- tpl (.Files.Get "files/api/settings/10-disable-caas.yaml") . | b64enc | nindent 4 }}
{{- end }}
