{{- $settings := .Values.settings -}}
{{- $authenticator := .Values.authenticator -}}
{{- $provider := .Values.provider -}}
{{- $apps := .Values.apps -}}
{{- $clusterEngine := .Values.clusterEngine -}}
{{- $keyStore := .Values.sshKeyStore -}}
{{- $ingress := mergeOverwrite (deepCopy .Values.global.ingress) .Values.ingress }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azimuth.componentname" (list . "api") }}
  labels: {{ include "azimuth.componentLabels" (list . "api") | nindent 4 }}
type: Opaque
stringData:
  01-django.yaml: |
    SECRET_KEY: {{ $settings.secretKey | default (randAlphaNum 64) }}
    DEBUG: {{ $settings.debug }}
    CSRF_COOKIE_SECURE: {{ $ingress.tls.enabled }}
    {{- with $settings.csrfCookieName }}
    CSRF_COOKIE_NAME: {{ . }}
    {{- end }}
    SESSION_COOKIE_SECURE: {{ $ingress.tls.enabled }}
    {{- with $settings.sessionCookieName }}
    SESSION_COOKIE_NAME: {{ . }}
    {{- end }}
    {{- with $settings.nextUrlCookieName }}
    AZIMUTH_AUTH:
      NEXT_URL_COOKIE_NAME: {{ . }}
    {{- end }}
  02-cloud-common.yaml: |
    AZIMUTH:
      AVAILABLE_CLOUDS:
        {{ $settings.currentCloud.name }}:
          label: {{ $settings.currentCloud.label }}
          url: {{ include "azimuth.externalUrl" . | printf "%s/dashboard" }}
        {{- range $settings.availableClouds }}
        {{ .name }}:
          label: {{ .label | quote }}
          url: {{ .url | quote }}
        {{- end }}
      CURRENT_CLOUD: {{ $settings.currentCloud.name }}
  03-cloud-authenticator.yaml: |
    AZIMUTH_AUTH:
      AUTHENTICATOR:
        {{- if (eq $authenticator.type "openstack-password") }}
        FACTORY: azimuth_auth.authenticator.openstack.PasswordAuthenticator
        PARAMS:
          AUTH_URL: {{ default $provider.openstack.authUrl $authenticator.openstackPassword.authUrl }}
          DOMAIN: {{ default $provider.openstack.domain $authenticator.openstackPassword.domain }}
          VERIFY_SSL: {{ default $provider.openstack.verifySsl $authenticator.openstackPassword.verifySsl }}
        {{- else if (eq $authenticator.type "openstack-federation") }}
        FACTORY: azimuth_auth.authenticator.openstack.FederatedAuthenticator
        PARAMS:
          FEDERATION_URL: {{ $authenticator.openstackFederation.federationUrl }}
        {{- else }}
        {{- fail (printf "Unrecognised authenticator '%s'" $authenticator.type) }}
        {{- end }}
  04-cloud-provider.yaml: |
    AZIMUTH:
      PROVIDER:
        {{- if (eq $provider.type "openstack") }}
        FACTORY: azimuth.provider.openstack.Provider
        PARAMS:
          AUTH_URL: {{ $provider.openstack.authUrl }}
          DOMAIN: {{ $provider.openstack.domain }}
          VERIFY_SSL: {{ $provider.openstack.verifySsl }}
          {{- with $provider.openstack.interface }}
          INTERFACE: {{ $provider.openstack.interface }}
          {{- end }}
          {{- with $provider.openstack.internalNetTemplate }}
          INTERNAL_NET_TEMPLATE: {{ . | quote }}
          {{- end }}
          {{- with $provider.openstack.externalNetTemplate }}
          EXTERNAL_NET_TEMPLATE: {{ . | quote }}
          {{- end }}
          CREATE_INTERNAL_NET: {{ $provider.openstack.createInternalNet }}
          {{- with $provider.openstack.internalNetCidr }}
          INTERNAL_NET_CIDR: {{ . | quote }}
          {{- end }}
        {{- else }}
        {{- fail (printf "Unrecognised cloud provider '%s'" $provider.type) }}
        {{- end }}
{{- if .Values.tags.apps }}
  05-apps.yaml: |
    # In order for the app authentication to work, the session cookie needs to apply to that domain
    # However we only do this if the portal host is within the apps domain
    # If not, we assume the Zenith installation is completely standalone with no auth
    {{- $host := tpl $ingress.host . }}
    {{- $baseDomain := tpl $apps.baseDomain . }}
    {{- if hasSuffix $baseDomain $host }}
    SESSION_COOKIE_DOMAIN: ".{{ $baseDomain }}"
    {{- end }}
    # We also need to allow redirects to the apps
    AZIMUTH_AUTH:
      NEXT_URL_ALLOWED_DOMAINS:
        - {{ quote $baseDomain }}
    AZIMUTH:
      APPS:
        ENABLED: true
        BASE_DOMAIN: {{ quote $baseDomain }}
        VERIFY_SSL: {{ ternary "yes" "no" $apps.verifySsl }}
        SSHD_HOST: {{ tpl $apps.sshdHost . | quote }}
        SSHD_PORT: {{ tpl (toString $apps.sshdPort) . | quote }}
        REGISTRAR_EXTERNAL_URL: {{ tpl $apps.registrarExternalUrl . | quote }}
        REGISTRAR_ADMIN_URL: {{ tpl $apps.registrarAdminUrl . | quote }}
        {{- with $apps.postDeployScriptUrl }}
        POST_DEPLOY_SCRIPT_URL: {{ . | quote }}
        {{- end }}
{{- end }}
  06-ssh-key-store.yaml: |
    AZIMUTH:
      SSH_KEY_STORE:
        {{- if (eq $keyStore.type "provider") }}
        FACTORY: azimuth.keystore.provider.ProviderKeyStore
        {{- else if (eq $keyStore.type "dummy") }}
        FACTORY: azimuth.keystore.dummy.DummyKeyStore
        PARAMS:
          KEY: {{ $keyStore.dummy.key | required "No key specified" }}
        {{- else if (eq $keyStore.type "ldap") }}
        FACTORY: azimuth.keystore.ldap.LdapKeyStore
        PARAMS:
          PRIMARY: {{ $keyStore.ldap.primary }}
          REPLICAS: {{ toYaml $keyStore.ldap.replicas | nindent 8 }}
          BASE_DN: {{ $keyStore.ldap.baseDn }}
        {{- else }}
        {{- fail (printf "Unrecognised key store '%s'" $keyStore.type) }}
        {{- end }}
{{- if not .Values.tags.kubernetes }}
  07-disable-kubernetes.yaml: |
    AZIMUTH:
      CLUSTER_API_PROVIDER: null
{{- end }}
{{- if .Values.tags.clusters }}
{{- if (eq $clusterEngine.type "awx") }}
  08-awx.yaml: |
    AZIMUTH:
      AWX:
        ENABLED: true
        URL: {{ tpl $clusterEngine.awx.url . | quote }}
        VERIFY_SSL: {{ $clusterEngine.awx.verifySsl }}
        USERNAME: {{ $clusterEngine.awx.username }}
        CREATE_TEAMS: {{ $clusterEngine.awx.createTeams }}
        CREATE_TEAM_ALLOW_ALL_PERMISSION: {{ $clusterEngine.awx.createTeamAllowAllPermission }}
        {{- with $clusterEngine.awx.adminUsername }}
        ADMIN_USERNAME: {{ . }}
        {{- end }}
        {{- if $clusterEngine.terraformBackend.enabled }}
        {{- if (eq $clusterEngine.terraformBackend.type "consul") }}
        EXTRA_CREDENTIALS:
          - NAME: CaaS Consul
            TYPE: Hashicorp Consul
            INPUTS:
              address: {{ tpl $clusterEngine.terraformBackend.consul.address . | quote }}
        {{- else }}
        {{- fail (printf "Unsupported terraform backend '%s'" $clusterEngine.terraformBackend.type) }}
        {{- end }}
        {{- end }}
        {{- with $clusterEngine.awx.defaultProjects }}
        DEFAULT_PROJECTS:
          {{- range . }}
          - NAME: {{ .name | quote }}
            GIT_URL: {{ .gitUrl }}
            GIT_VERSION: {{ .gitVersion }}
            METADATA_ROOT: {{ .metadataRoot }}
            {{- with .alwaysUpdate }}
            ALWAYS_UPDATE: {{ . | ternary "true" "false" }}
            {{- end }}
            {{- with .executionEnvironment }}
            EXECUTION_ENVIRONMENT:
              IMAGE: {{ .image | quote }}
              {{- with .alwaysPull }}
              ALWAYS_PULL: {{ .alwaysPull | ternary "true" "false" }}
              {{- end }}
            {{- end }}
            {{- with .playbooks }}
            PLAYBOOKS: {{ toYaml . | nindent 14 }}
            {{- end }}
            {{- with .extraVars }}
            EXTRA_VARS: {{ toYaml . | nindent 14 }}
            {{- end }}
          {{- end }}
        {{- end }}
  09-awx-passwords.py: |
    import os
    # Read the AWX password from an environment variable that is populated from the specified secret
    AZIMUTH['AWX']['PASSWORD'] = os.environ['AWX_PASSWORD']
    if 'AWX_ADMIN_PASSWORD' in os.environ:
        AZIMUTH['AWX']['ADMIN_PASSWORD'] = os.environ['AWX_ADMIN_PASSWORD']
{{- else }}
{{- fail (printf "Unsupported cluster engine '%s'" $clusterEngine.type) }}
{{- end }}
{{- end }}
