---

guacamole_image_prefix: ghcr.io/stackhpc

guacamole_server_image_name: guacd
guacamole_server_image_tag: latest
guacamole_server_image: "{{ guacamole_image_prefix }}/{{ guacamole_server_image_name }}:{{ guacamole_server_image_tag }}"
guacamole_server_image_pull: no

guacamole_client_image_name: guacamole
guacamole_client_image_tag: latest
guacamole_client_image: "{{ guacamole_image_prefix }}/{{ guacamole_client_image_name }}:{{ guacamole_client_image_tag }}"
guacamole_client_image_pull: no

guacamole_ssh_user: centos

# TODO: PULL THIS FROM INSTANCE METADATA
guacamole_password_hash: "{{ 'portal' | hash('md5') }}"
