"""initial

Revision ID: 2da92b07e42
Revises: 
Create Date: 2015-10-26 16:31:27.246903

"""

# revision identifiers, used by Alembic.
revision = '2da92b07e42'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cloud_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allow_inbound', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalogue_meta')
    ### end Alembic commands ###
