{{- $component := "ui" -}}
{{- $values := get .Values $component -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azimuth.componentname" (list . $component) }}
  labels: {{ include "azimuth.componentLabels" (list . $component) | nindent 4 }}
spec:
  replicas: {{ $values.replicaCount }}
  selector:
    matchLabels:
      {{- include "azimuth.componentSelectorLabels" (list . $component) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "azimuth.componentSelectorLabels" (list . $component) | nindent 8 }}
      annotations:
        azimuth.stackhpc.com/theme-checksum: {{ include (print $.Template.BasePath "/configmap-theme.yaml") . | sha256sum }}
        {{- with $values.podAnnotations }}
        {{ toYaml . | indent 8 | trim }}
        {{- end }}
    spec:
      {{- with $values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{ toYaml $values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $component }}
          securityContext: {{ toYaml $values.securityContext | nindent 12 }}
          image: {{ printf "%s:%s" $values.image.repository (default .Chart.AppVersion $values.image.tag) }}
          imagePullPolicy: {{ $values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with $values.livenessProbe }}
          livenessProbe: {{ toYaml $values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- with $values.readinessProbe }}
          readinessProbe: {{ toYaml $values.readinessProbe | nindent 12 }}
          {{- end }}
          resources: {{ toYaml $values.resources | nindent 12 }}
          volumeMounts:
            - name: theme-css
              mountPath: /var/www/bootstrap.css
              subPath: bootstrap.css
            - name: var-cache-nginx
              mountPath: /var/cache/nginx
            - name: var-run-nginx
              mountPath: /var/run/nginx
      {{- with $values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: theme-css
          configMap:
            name: {{ include "azimuth.componentname" (list . "theme") }}
        - name: var-cache-nginx
          emptyDir: {}
        - name: var-run-nginx
          emptyDir: {}
