---
name: Publish artifacts

on:
  # Publish artifacts on every push to master and every tag
  push:
    branches:
      - master
    tags:
      - "*"
  # Also allow publication to be done via a workflow call
  # In this case, the chart version is returned as an output
  workflow_call:
    inputs:
      ref:
        type: string
        description: The ref to build.
        required: true
    outputs:
      chart-version:
        description: The chart version that was published
        value: ${{ jobs.build_push_chart.outputs.chart-version }}

env:
  NGINX_VERSION: 1.29.8

jobs:
  build_push_images:
    name: Build and push images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - component: api
          - component: ui
    permissions:
      contents: read
      id-token: write         # needed for signing the images with GitHub OIDC Token
      packages: write         # required for pushing container images
      security-events: write  # required for pushing SARIF files
    steps:
      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get SemVer version for current commit
        id: semver
        uses: azimuth-cloud/github-actions/semver@master

      - name: Calculate metadata for image
        id: image-meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: ghcr.io/azimuth-cloud/azimuth-${{ matrix.component }}
          # Produce the branch name or tag and the SHA as tags
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=${{ steps.semver.outputs.short-sha }}

      - name: Build and push image
        uses: azimuth-cloud/github-actions/docker-multiarch-build-push@master
        with:
          cache-key: ${{ matrix.component }}
          context: ./${{ matrix.component }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.image-meta.outputs.tags }}
          labels: ${{ steps.image-meta.outputs.labels }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build_push_chart:
    name: Build and push Helm chart
    runs-on: ubuntu-latest
    # Only build and push the chart if the images built successfully
    needs: [build_push_images]
    outputs:
      chart-version: ${{ steps.semver.outputs.version }}
    permissions:
      contents: write
      id-token: none
      packages: none
      security-events: none
    steps:
      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.ref || github.ref }}
          # This is important for the semver action to work correctly
          # when determining the number of commits since the last tag
          fetch-depth: 0

      - name: Get SemVer version for current commit
        id: semver
        uses: azimuth-cloud/github-actions/semver@master

      - name: Publish Helm charts
        uses: azimuth-cloud/github-actions/helm-publish@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.semver.outputs.version }}
          app-version: ${{ steps.semver.outputs.short-sha }}
