# This workflow proposes updates to the dependencies that dependabot cannot
name: Update dependencies

on:
  # Allow manual executions
  workflow_dispatch:
  # Run nightly
  schedule:
    - cron: '0 0 * * *'

jobs:
  propose_github_release_updates:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - key: nginx
            path: ./.github/workflows/build-push-artifacts.yaml
            repository: nginxinc/docker-nginx
            # This repository only publishes tags, not releases
            tags: "yes"
            version_jsonpath: env.NGINX_VERSION
            component: ui

          - key: statsd-exporter
            path: ./chart/values.yaml
            repository: prometheus/statsd_exporter
            version_jsonpath: api.monitoring.statsd.image.tag
            component: api

    name: ${{ matrix.key }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for most recent GitHub release
        id: next
        uses: azimuth-cloud/github-actions/github-latest-release@master
        with:
          repository: ${{ matrix.repository }}
          tags: ${{ matrix.tags || 'no' }}

      - name: Update dependency key
        uses: azimuth-cloud/github-actions/config-update@master
        with:
          path: ${{ matrix.path }}
          updates: |
            ${{ matrix.version_jsonpath }}=${{ steps.next.outputs.version }}

      - name: Generate app token for PR
        uses: azimuth-cloud/github-actions/generate-app-token@master
        id: generate-app-token
        with:
          repository: ${{ github.repository }}
          app-id: ${{ secrets.AUTOMATION_APP_ID }}
          app-private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}

      - name: Propose changes via PR if required
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-app-token.outputs.token }}
          commit-message: >-
            Bump ${{ matrix.key }} to ${{ steps.next.outputs.version }}
          branch: update-dependency/${{ matrix.key }}
          delete-branch: true
          title: >-
            Bump ${{ matrix.key }} to ${{ steps.next.outputs.version }}
          body: >
            This PR was created automatically to update
            ${{ matrix.key }} to ${{ steps.next.outputs.version }}.
          labels: |
            automation
            dependency-update
            ${{ matrix.component }}
